
const int HIVE_TYPE_ID_ACTOR_VO = 1;
const int HIVE_TYPE_ID_BASE_ACTOR_VO = 2;
const int HIVE_TYPE_ID_COLLECTION_VO = 3;
const int HIVE_TYPE_ID_CREDIT_VO = 4;
const int HIVE_TYPE_ID_DATE_VO = 5;
const int HIVE_TYPE_ID_GENRE_VO = 6;
const int HIVE_TYPE_ID_MOVIE_VO = 7;
const int HIVE_TYPE_ID_PRODUCTION_COMPANY_VO = 8;
const int HIVE_TYPE_ID_PRODUCTION_COUNTRY_VO = 9;
const int HIVE_TYPE_ID_SPOKEN_LANGUAGE_VO = 10;

const int HIVE_TYPE_ID_USER_VO = 11;
const int HIVE_TYPE_ID_CARD_VO = 12;
const int HIVE_TYPE_ID_SNACKS_VO = 13;
const int HIVE_TYPE_ID_CINEMA_DAY_TIME_VO = 14;
const int HIVE_TYPE_ID_DAY_TIME_SLOT_VO = 15;
const int HIVE_TYPE_ID_TIME_SLOT_VO = 16;
const int HIVE_TYPE_ID_PAYMENT_VO = 17;

const BOX_NAME_USER_VO = "BOX_NAME_USER_VO";

const BOX_NAME_ACTOR_VO = "BOX_NAME_ACTOR_VO";
const BOX_NAME_BASE_ACTOR_VO = "BOX_NAME_BASE_ACTOR_VO";
const BOX_NAME_COLLECTION_VO = "BOX_NAME_COLLECTION_VO";
const BOX_NAME_CREDIT_VO = "BOX_NAME_CREDIT_VO";
const BOX_NAME_DATE_VO = "BOX_NAME_DATE_VO";
const BOX_NAME_GENRE_VO = "BOX_NAME_GENRE_VO";
const BOX_NAME_MOVIE_VO = "BOX_NAME_MOVIE_VO";
const BOX_NAME_PRODUCTION_COMPANY_VO = "BOX_NAME_PRODUCTION_COMPANY_VO";
const BOX_NAME_PRODUCTION_COUNTRY_VO = "BOX_NAME_PRODUCTION_COUNTRY_VO";
const BOX_NAME_SPOKEN_LANGUAGE_VO = "BOX_NAME_SPOKEN_LANGUAGE_VO";
const BOX_NAME_CARD_VO = "BOX_NAME_CARD_VO";
const BOX_NAME_SNACKS_VO = "BOX_SNACKS_VO";
const BOX_NAME_PAYMENT_VO = "BOX_PAYMENT_VO";
const BOX_NAME_CINEMA_DAY_TIME_VO = "BOX_NAME_CINEMA_DAY_TIME_VO";
const BOX_NAME_DAY_TIME_SLOTS_VO = "BOX_NAME_DAY_TIME_SLOTS_VO";
const BOX_NAME_TIME_SLOTS_VO = "BOX_NAME_TIME_SLOTS_VO";
